// Configuration: Vehicle Models to Brand Mapping
module.exports = {
    // Chevrolet
    'AVEO': 'CHEVROLET',
    'SPARK': 'CHEVROLET',
    'CORSA': 'CHEVROLET',
    'SAIL': 'CHEVROLET',
    'DMAX': 'CHEVROLET',
    'D-MAX': 'CHEVROLET',
    'COBALT': 'CHEVROLET',
    'SONIC': 'CHEVROLET',
    'CRUZE': 'CHEVROLET',
    'CAPTIVA': 'CHEVROLET',
    'TRACKER': 'CHEVROLET',
    'ONIX': 'CHEVROLET',
    'CRONOS': 'CHEVROLET',
    'NKR': 'CHEVROLET',
    'NHR': 'CHEVROLET',
    'VITARA': 'CHEVROLET',

    // Toyota
    'HILUX': 'TOYOTA',
    'HI-LUX': 'TOYOTA',
    'FORTUNER': 'TOYOTA',
    'PRADO': 'TOYOTA',
    'LAND CRUISER PRADO': 'TOYOTA',
    'CAMRY': 'TOYOTA',
    'COROLLA': 'TOYOTA',
    'YARIS': 'TOYOTA',
    'RAV4': 'TOYOTA',
    'RAV-4': 'TOYOTA',
    '4RUNNER': 'TOYOTA',
    'LAND CRUISER': 'TOYOTA',
    'VIGO': 'TOYOTA',
    'REVO': 'TOYOTA',
    'ETIOS': 'TOYOTA',
    'RUSH': 'TOYOTA',

    // Nissan
    'SENTRA': 'NISSAN',
    'VERSA': 'NISSAN',
    'TIIDA': 'NISSAN',
    'FRONTIER': 'NISSAN',
    'XTRAIL': 'NISSAN',
    'X-TRAIL': 'NISSAN',
    'QASHQAI': 'NISSAN',
    'KICKS': 'NISSAN',
    'URVAN': 'NISSAN',
    'NP300': 'NISSAN',
    'NAVARA': 'NISSAN',
    'PATHFINDER': 'NISSAN',
    'MURANO': 'NISSAN',

    // Hyundai
    'TUCSON': 'HYUNDAI',
    'ELANTRA': 'HYUNDAI',
    'ACCENT': 'HYUNDAI',
    'I10': 'HYUNDAI',
    'ION': 'HYUNDAI',
    'GRAND I10': 'HYUNDAI',
    'GRAND': 'HYUNDAI',
    'I25': 'HYUNDAI',
    'I35': 'HYUNDAI',
    'VISION': 'HYUNDAI',
    'VERNA': 'HYUNDAI',
    'ATOS': 'HYUNDAI',
    'GYRO': 'HYUNDAI',
    'H100': 'HYUNDAI',
    'SANTAFE': 'HYUNDAI',
    'SANTA FE': 'HYUNDAI',
    'VELOSTER': 'HYUNDAI',
    'CRETA': 'HYUNDAI',

    // KIA
    'CERATO': 'KIA',
    'PICANTO': 'KIA',
    'SORENTO': 'KIA',
    'SOUL': 'KIA',
    'FORTE': 'KIA',
    'PREGIO': 'KIA',
    'CARNIVAL': 'KIA',
    'RIO': 'KIA',
    'RISE': 'KIA',
    'SPORTAGE': 'KIA',
    'SELTOS': 'KIA',
    'STONIC': 'KIA',

    // Renault
    'LOGAN': 'RENAULT',
    'SANDERO': 'RENAULT',
    'DUSTER': 'RENAULT',
    'CLIO': 'RENAULT',
    'CLIOII': 'RENAULT',
    'CLIO II': 'RENAULT',
    'SYMBOL': 'RENAULT',
    'MEGANE': 'RENAULT',
    'SCENIC': 'RENAULT',
    'STEPWAY': 'RENAULT',
    'KANGOO': 'RENAULT',
    'MASTER': 'RENAULT',
    'ALASKAN': 'RENAULT',
    'KOLEOS': 'RENAULT',
    'CAPTUR': 'RENAULT',
    '12': 'RENAULT',

    // Mazda
    'CX5': 'MAZDA',
    'CX-5': 'MAZDA',
    'CX-30': 'MAZDA',
    'CX30': 'MAZDA',
    'CX50': 'MAZDA',
    'CX-50': 'MAZDA',
    'BT50': 'MAZDA',
    'BT-50': 'MAZDA',
    'M2': 'MAZDA',
    'M3': 'MAZDA',
    'M323': 'MAZDA',
    'M2600': 'MAZDA',
    'M626': 'MAZDA',
    'B2000': 'MAZDA',
    'B2200': 'MAZDA',
    '121': 'MAZDA',
    '3': 'MAZDA',
    '6': 'MAZDA',
    'DEMIO': 'MAZDA',

    // Otras marcas...
    'FIESTA': 'FORD',
    'ECOSPORT': 'FORD',
    'RANGER': 'FORD',
    'F-150': 'FORD',

    'GOL': 'VOLKSWAGEN',
    'JETTA': 'VOLKSWAGEN',
    'AMAROK': 'VOLKSWAGEN',

    'MOBI': 'FIAT',
    'UNO': 'FIAT',
    'STRADA': 'FIAT',

    'SWIFT': 'SUZUKI',
    'VITARA': 'SUZUKI',
    'JIMNY': 'SUZUKI',

    'CIVIC': 'HONDA',
    'CR-V': 'HONDA',
    'CRV': 'HONDA',

    'IMPREZA': 'SUBARU',
    'FORESTER': 'SUBARU',

    'D-MAX': 'ISUZU',
    'DMAX': 'ISUZU',
    'MU-X': 'ISUZU'
};
